CREATE TABLE IF NOT EXISTS users(
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    isAdmin BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS urls(
    id VARCHAR(255) UNIQUE NOT NULL,
    longUrl VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS logs(
    log_id SERIAL PRIMARY KEY,
    url_id VARCHAR(255) REFERENCES urls(id),
    device VARCHAR(255),
    os VARCHAR(255),
    country VARCHAR(255),
    city VARCHAR(255),
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

